[package]
name = "main"
version = "0.1.0"
authors = ["Thomas Nicollet <thomasnicollet@yahoo.fr>"]
edition = "2018"

[dependencies]
network_variables = { path = "../network_variables" }
packets = { path = "../packets" }